export const INITIAL_SIZE = 250,
  INITIAL_WIND = [5.0, 10.0],
  INITIAL_CHOPPINESS = 1.5;

export const CLEAR_COLOR = [1.0, 1.0, 1.0, 0.0],
  GEOMETRY_ORIGIN = [-1000.0, -1000.0],
  SUN_DIRECTION = [-1.0, 1.0, 1.0],
  OCEAN_COLOR = [0.004, 0.016, 0.047],
  SKY_COLOR = [3.2, 9.6, 12.8],
  EXPOSURE = 0.35,
  GEOMETRY_RESOLUTION = 256,
  GEOMETRY_SIZE = 2000,
  RESOLUTION = 512;

export const SIZE_OF_FLOAT = 4;

export const OCEAN_COORDINATES_UNIT = 1;

export const INITIAL_SPECTRUM_UNIT = 0,
  SPECTRUM_UNIT = 1,
  DISPLACEMENT_MAP_UNIT = 2,
  NORMAL_MAP_UNIT = 3,
  PING_PHASE_UNIT = 4,
  PONG_PHASE_UNIT = 5,
  PING_TRANSFORM_UNIT = 6,
  PONG_TRANSFORM_UNIT = 7;

export const UI_COLOR = "rgb(52, 137, 189)";

export const PROFILE_AMPLITUDE = 50,
  PROFILE_OMEGA = 0.05,
  PROFILE_PHI = -2.5,
  PROFILE_STEP = 5,
  PROFILE_OFFSET = 52,
  PROFILE_COLOR = "rgb(52, 137, 189)",
  PROFILE_LINE_WIDTH = 3,
  CHOPPINESS_SCALE = 0.15;

export const ARROW_ORIGIN = [-1250, 0, 500],
  ARROW_SHAFT_WIDTH = 80,
  ARROW_HEAD_WIDTH = 160,
  ARROW_HEAD_HEIGHT = 60,
  ARROW_OFFSET = 40,
  WIND_SCALE = 8.0,
  MIN_WIND_SPEED = 5.0,
  MAX_WIND_SPEED = 25.0;

export const HANDLE_COLOR = "#666666",
  SLIDER_LEFT_COLOR = UI_COLOR,
  SLIDER_RIGHT_COLOR = "#999999";

export const FOV = (60 / 180) * Math.PI,
  NEAR = 1,
  FAR = 10000,
  MIN_ASPECT = 16 / 9;

export const WIND_SPEED_DECIMAL_PLACES = 1,
  SIZE_DECIMAL_PLACES = 0,
  CHOPPINESS_DECIMAL_PLACES = 1;

export const SENSITIVITY = 1.0;

export const WIND_SPEED_X = -1350;
export const MIN_WIND_SPEED_Z = 600,
  WIND_SPEED_OFFSET = 30;

export const OVERLAY_DIV_ID = "overlay",
  PROFILE_CANVAS_ID = "profile",
  SIMULATOR_CANVAS_ID = "simulator",
  UI_DIV_ID = "ui",
  CAMERA_DIV_ID = "camera",
  WIND_SPEED_DIV_ID = "wind",
  WIND_SPEED_SPAN_ID = "wind-speed",
  CHOPPINESS_DIV_ID = "choppiness";

export const SIZE_SLIDER_X = -200,
  SIZE_SLIDER_Z = 1100,
  SIZE_SLIDER_LENGTH = 400,
  MIN_SIZE = 100,
  MAX_SIZE = 1000,
  SIZE_SLIDER_BREADTH = 3,
  SIZE_HANDLE_SIZE = 24;

export const CHOPPINESS_SLIDER_X = -1420,
  CHOPPINESS_SLIDER_Z = 75,
  CHOPPINESS_SLIDER_LENGTH = 300,
  MIN_CHOPPINESS = 0,
  MAX_CHOPPINESS = 2.5,
  CHOPPINESS_SLIDER_BREADTH = 6,
  CHOPPINESS_HANDLE_SIZE = 30;

export const ARROW_TIP_RADIUS = 100,
  SIZE_HANDLE_RADIUS = 30,
  CHOPPINESS_HANDLE_RADIUS = 100;

export const NONE = 0,
  ORBITING = 1,
  ROTATING = 2,
  SLIDING_SIZE = 3,
  SLIDING_CHOPPINESS = 4;

export const CAMERA_DISTANCE = 1500,
  ORBIT_POINT = [-200.0, 0.0, 600.0],
  INITIAL_AZIMUTH = 0.4,
  INITIAL_ELEVATION = 0.5,
  MIN_AZIMUTH = -0.2,
  MAX_AZIMUTH = 0.5,
  MIN_ELEVATION = 0.4,
  MAX_ELEVATION = 0.8;
